### ISSUE TITLE
Bloated codebase

### ISSUE THREAD

**Issue by Batey96** [internetarchive/iaux#103]
**Is your feature request related to a problem? Please describe.**
> Developers new to the code-base become overwhelm by fact that there is significantly more code than required.Hence sometimes difficult to keep track when studying the code-base

**Describe the solution you'd like**
> Refactoring the code-base and adhering to a unique clean pattern

**Stakeholders**
> @ tag stakeholders of this feature

**Comment by iisa** [comment]
Thanks for this, @Batey96! We are actively making this happen and have strategized around this - especially around ease of maintenance and ease of community contribution.  Will close this for now, and will announce in our slack channel when we have something more concrete.
