### ISSUE TITLE
Babel issue making ia-components accessible by other packages

### ISSUE THREAD

**Issue by mitra42** [internetarchive/iaux#107]
I'm trying to use the newly merged components from dweb-archive, but ... getting errors from Babel. 

To see the problem these steps should work ... 
```
clone https://github.com/internetarchive/dweb-archive.git#iaux // Note its the iaux branch
yarn install // Will get ia-components canary
```
There are three possible ways to include `TileImage` from `components/tiles/TileComponent.js`:
#### 1: `import TileImage from "./TileImage";`

then webpack --mode development  works, proving that the problem isn't with the file itself.

#### 2: `import TileImage from "@internetarchive/ia-components/sandbox/tiles/TileImage.js"`

gets the following error :
```
ERROR in ./node_modules/@internetarchive/ia-components/sandbox/tiles/TileImage.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/mitra/git/dweb-archive/node_modules/@internetarchive/ia-components/sandbox/tiles/TileImage.js: Unexpected token (29:19)

  27 |         if (typeof DwebArchive !== "undefined") {
  28 |             //TODO-DWEB build img processing from ReactFake into tile-tile-image and ParentTileImg but wait till have non-tile images as well
> 29 |             return <span ref={this.load}></span>
     |                    ^
  30 |         } else {
```
Which looks like the JSX transpile isn't happening. 

#### 3: `import TileImage from "@internetarchive/ia-components";`

Gets a lot of errors - some in each of the files  as I think its trying to load all of ia-components.

**Comment by mitra42** [comment]
@shreyansh23 I think you are the Babel expert, could you take a look. I'm not sure if the fix is needed in dweb-archive, or in ia-components,  I'm hoping its in the latter to make it easier to include ia-components in other things, but if the problem is in dweb-archive, then I'm guessing its in `.babelrc` or `webpack.config.js` and it looks like the webpack.config has already been edited to try and not exclude modules in node_modules/@internetarchive from babel.

**Comment by shreyansh23** [comment]
@mitra42 I am definitely not an expert :sweat_smile: but would like to give my try on this issue.

Can you please confirm the branch? I couldn't find branch named iaux in dweb-archive.

**Comment by shreyansh23** [comment]
Another note, the import problem here is similar to the ones coming on running `ia-prototype-apps`.
See issue  #65, #81

**Comment by mitra42** [comment]
Oops - my mistake @shreyansh23 , that branch wasn't just local to my machine. It should be pushed to github now

**Comment by mitra42** [comment]
@shreyansh23 - any luck with this ?

**Comment by shreyansh23** [comment]
@mitra42 really sorry I couldn't investigate much since my finals are going on. It will take just few more days to end.

**Comment by shreyansh23** [comment]
@mitra42 finally on experimenting and reading more docs on Babel 7, I found that the problem was coming because of the presets. The necessary the presets are already specified `.babelrc` file but for some reason, they are not working from there.

Therefore specifying the presets in `webpack.config.js` itself makes them work correctly.

Please see PR https://github.com/internetarchive/dweb-archive/pull/98. Testing steps are mentioned in the description itself.

Also, let me know if anything more needs to be done or I am wrong on any point.

**Comment by shreyansh23** [comment]
@mitra42 I saw you have approved and merged the changes. Should this issue be closed?

**Comment by mitra42** [comment]
Thanks for the changes ... worked as described, I left it open because there are two more steps
a) switch those components to use .jsx as requested by @iisa   which I think will break the changes you made,
b) include files from the top level i.e. from ia-components/index.js which may or may not break the changes. 

I haven't yet had time to make & test those changes, which is why its still open. 

The good thing ... is that now this works I've moved most of my components into IAUX and Isa approved the merge yesterday, so that makes them all available as bases to build on.

**Comment by mitra42** [comment]
Closing as both those steps worked
