### ISSUE TITLE
Setup fails due to erros in ia-js-client package

### ISSUE THREAD

**Issue by Batey96** [internetarchive/iaux#108]
**Description**
ON a fresh clone and install,errors are being encountered when bootstrapping the packages.This is as a result of typo errors in the ia-js-client package..

**Steps To Reproduce**
```
git clone https://github.com/internetarchive/iaux.git
cd "cloned Repo"
yarn install 
yarn run lerna bootstrap
```

![iajsfail](https://user-images.githubusercontent.com/24868289/56456896-aeb08d00-636a-11e9-996b-60f9020ed0ae.png)

**Comment by mitra42** [comment]
Are any of them a result of the changes I made recently ? 

I need a scroll-up on your screen shot, as I can't see what you are running that generates these errors, can you post the STR and I'll check the bugs aren't something I introduced.

**Comment by Batey96** [comment]
Yes i think so.the recent changes made the bug!..because i compared it with an older ia-js-client package and bootstrapping was okay..the additions you made handling fallbacks are a source of it..typo errors which i fixed.PR sent

**Comment by Batey96** [comment]
PR 109

**Comment by mitra42** [comment]
Thanks - I posted comments in

**Comment by Batey96** [comment]
Steps To Reproduce
```
git clone https://github.com/internetarchive/iaux.git
cd  "cloned Repo"
yarn install
yarn run lerna bootstrap
```

**Comment by mitra42** [comment]
Thanks @Batey96 for adding them above.

**Comment by Batey96** [comment]
Issue resolved
