### ISSUE TITLE
Add jsdoc 

### ISSUE THREAD

**Issue by mitra42** [internetarchive/iaux#137]
**Task Details**
Sample doc sent from ISA in Slack just now
**Verification**
?
**Stakeholders**
@mitra42 @iisa

**Comment by mitra42** [comment]
I'm working through these one by one, including where appropriate tidying up the component  in which case I'll submit as a separate PR.

**Comment by iisa** [comment]
thanks @mitra42 , we will continue to forge our way through proper documentation 1 PR at a time.
