### ISSUE TITLE
ArchiveMember.js cannot resolve during webpack build

### ISSUE THREAD

**Issue by iisa** [internetarchive/iaux#153]
![image](https://user-images.githubusercontent.com/7840857/57891168-4204a300-77ef-11e9-8bfe-2245481f9a2b.png)

Internal Petabox build is breaking due to ArchiveMember.js not included.
Planned with @mitra42 to possibly include `@internetarchive/dweb-archivecontroller` into ia-components.
He is confirming that `@internetarchive/dweb-archivecontroller` dependencies are correct and up to date.

**Comment by mitra42** [comment]
Note the conclusion was that there is a balance between component-encapsulation and not creating dependencies on controllers in lower-level components, and best way is to have component at higher level pass down the data. For now moved back to dweb-archive until that higher level component is ready
