### ISSUE TITLE
Installation steps fails for Ubuntu 18.04

### ISSUE THREAD

**Issue by shreyansh23** [internetarchive/iaux#16]
On installing the project using the instructions in README.md. The steps fails at some points.
This includes:
- error due to fsevents package
- babal-core version error

**Comment by Batey96** [comment]
exactly what i faced.Did  some research and found out fsevent no more supported on linux Os.
To erase the yarn instance warning,simply run the instances parralelly with this on the terminal:
**yarn run lerna bootstrap --concurrency=1*

**Comment by Batey96** [comment]
exactly what i faced.Did some research and found out fsevent no more supported on linux Os.
To erase the yarn instance warning,simply run the instances parralelly with this on the terminal:
**yarn run lerna bootstrap --concurrency=1**

**Comment by shreyansh23** [comment]
Yes @Batey96 `fsevents` do not support linux. The correct way of using that module is putting it in optional dependencies. Please see the PR. I shared the relevant resources in the comments.

**Comment by shreyansh23** [comment]
Issue solved in #22
Closing this issue.
