### ISSUE TITLE
Flatten Directory Structure of ia-components sandbox

### ISSUE THREAD

**Issue by iisa** [internetarchive/iaux#169]
**Task Details**

components should live in a flattened directory inside of live & sandbox directories.

Task:
[ ] move `components` in theatres directory to top level
[ ] make sure all import & export references are working 
[ ] make sure all examples are running inside storybook
[ ] Identify other components that can be moved to the flatter structure

Items @koderjoker and I have identified:
- [ ] https://github.com/internetarchive/iaux/projects/1#card-22373624

**Verification**

When list above is complete

**Stakeholders**

**Comment by iisa** [comment]
@koderjoker when doing this, let's make this the main issue to track progress.  We can do smaller PRs are you flatten parts of the code and we will create a master list in this issue.  That way you are not left with a giant block to push through.  Also, we can make smaller tickets to reflect the smaller PRs.   How does that sound?

**Comment by koderjoker** [comment]
Sounds great!
