### ISSUE TITLE
Handling errors in the youtube player 

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#213]
**Task Details**
![Error handling](https://user-images.githubusercontent.com/30471843/59980003-405ba580-960d-11e9-93f8-602b6687ed4d.gif)
Currently, in our youtube player, we immediately skip a track in case of the following 
- Requesting an invalid id
- Errors regarding the HTML5 player
- Video requested was not found (Video has been removed or has been marked as private)
- Owner of the requested video does not allow it to be played in embedded players

Aim is to tackle errors in a better manner.

**Temporary solution**
To give a time lag (approx 3s) so that a user can see the error displayed, before moving on to the next track.

**Long term solutions**
- Mark tracks with errors as 'Unavailable' and mark them in grey
or
- Not displaying tracks with errors in the youtube channel

**Comment by iisa** [comment]
done
