### ISSUE TITLE
Stop autoplaying the youtube player after changing channels

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#222]
Task Details
Currently, our youtube player autoplays the selected track after switching channels. Our aim is to make sure the selected track doesn't autoplay after doing so.

**Comment by Batey96** [comment]
Hey Koder,is it similar to my PR #128?

**Comment by koderjoker** [comment]
Nope, since this one deals with the youtube component (youtube-player.jsx). 

The music player has seen many changes since then.

**Comment by iisa** [comment]
done
