### ISSUE TITLE
settimeout and autoplay disrupt normal track progression

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#223]
**Task Details**
After clicking Angel followed by Same Ole Love, tracks play unconsecutively because every track is trying to complete their settimeout and autoplay.
(Angel, You’re the Best Thing Yet, Same Ole Love and No One in the World are tracks with errors)

![Jul-02-2019 01-27-50](https://user-images.githubusercontent.com/30471843/60463809-91e9dd00-9c6a-11e9-900b-593fa4b4a78f.gif)

**Comment by iisa** [comment]
done
