### ISSUE TITLE
Implement hamburger menu

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#249]
**Task Details**

The following issue is to serve as a task list of issues pertaining to our **hamburger menu**

Mockup for the same with components marked
![Screen Shot 2019-08-01 at 3 19 39 AM](https://user-images.githubusercontent.com/30471843/62250710-495d4500-b40b-11e9-982f-45003dcf3bdb.png)

Subtasks
- [ ] **Issue #250:** Implement sliders for iconochive icon sections
- [ ] **Issue #251:** Implement slider for more section

**Comment by iisa** [comment]
@koderjoker closing as this has been merged
