### ISSUE TITLE
Implement sliders for iconochive icon sections

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#250]
**Task Details**

The following issue aims at implementing sliders for the **iconochive icon sections** which include the Wayback Machine, Texts, Video, Audio, Software and Images.

Mockup for the Audio Section
![Screen Shot 2019-08-01 at 3 28 00 AM](https://user-images.githubusercontent.com/30471843/62251164-7cec9f00-b40c-11e9-80fb-12a5ca56ca89.png)

**Comment by iisa** [comment]
@koderjoker closing as I see that this is merged.
