### ISSUE TITLE
Implement slider for more section

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#251]
**Task Details**

The following issue aims at implementing a slider for the **more section**.

Mockup for the more section
![Screen Shot 2019-08-01 at 3 31 31 AM](https://user-images.githubusercontent.com/30471843/62251294-eb316180-b40c-11e9-9c56-cc5182e4e8bd.png)

**Comment by iisa** [comment]
@koderjoker closing seeing that this is merged.
