### ISSUE TITLE
Reduce search field to a magnifying glass icon

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#29]
**Is your feature request related to a problem? Please describe.**
The following issue aims at making the navbar more accessible.
The items on the navbar take up too much space which makes it difficult to increase their tap target size (issue #27). 
![Screen Shot 2019-03-25 at 8 41 18 PM](https://user-images.githubusercontent.com/30471843/54931157-820d7f00-4f3e-11e9-98e5-778be2dd2b6a.png)

**Describe the solution you'd like**
In order to save space on the navbar, reduce the search field to a magnifying glass icon which expands into a search field just below the navbar on selection (for screen width <768px)

**Proposal & Constraints**
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

A good example of such an implementation would be the search used at [css-tricks](https://css-tricks.com/)

**Comment by mekarpeles** [comment]
@jimbonator this may be relevant to some of the work you're doing

**Comment by mekarpeles** [comment]
@pezvi this may be relevant to some of the work you're doing

**Comment by pezvi** [comment]
This is a great issue. Thanks for document it. It overlaps with a mobile navbar design we're currently handling internally, which will resolve this issue. I'm closing this issue here.
