### ISSUE TITLE
Shifting Internet Archive's logo to the left

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#30]
**Is your feature request related to a problem? Please describe.**
The following issue aims at making user navigation easier.
Research says that logos aligned on the left are better for navigation, and are easier for users to remember. Also, since there are already many icons on the navbar, for certain screen widths the Internet Archive's logo seems a bit lost in between.
![Screen Shot 2019-03-25 at 9 11 38 PM](https://user-images.githubusercontent.com/30471843/54933430-a0757980-4f42-11e9-847c-bf34cb1e374d.png)

**Describe the solution you'd like**
Even though the current placement is an awesome stylistic choice for >=768px, should Internet Archive’s logo be aligned to the left?

**Comment by akshaykumar23399** [comment]
Did you want to shift the logo to left and i have one more suggestions that we can create a menu column in which user get all navbar icon

**Comment by pezvi** [comment]
There's redesign in progress on the topnav bnar. Claiming this one internally.
