### ISSUE TITLE
Main Menu: clicking labels should also open up secondary window.

### ISSUE THREAD

**Issue by iisa** [internetarchive/iaux#316]
Problem:
Clicking on main menu label does not open up secondary menu.

![main-menu-click-label](https://user-images.githubusercontent.com/7840857/66335780-91f41b80-e8f0-11e9-808a-6e97631a7304.gif)

Acceptance:
- Clicking main menu labels opens secondary menu.
- icon and label is 1 group.

**Comment by shaneriley** [comment]
Looks like this was fixed. Closing.
