### ISSUE TITLE
Main Menu: clicking on icon does not bring up secondary menu

### ISSUE THREAD

**Issue by iisa** [internetarchive/iaux#317]
Problem:
Flow: click on main menu hamburger to open main menu > click on icon to open up secondary menu > click on next main menu icon > secondary menu closes and does not display the next selection's secondary menu.  See gif

![main-menu-secondary-click](https://user-images.githubusercontent.com/7840857/66336257-9967f480-e8f1-11e9-8dc3-b8d512f8ead6.gif)

Acceptance:
On click of a main menu's icon, its secondary menu shows.

**Comment by shaneriley** [comment]
I think this was fixed as well.
