### ISSUE TITLE
Main Menu: on close, secondary menu should also close

### ISSUE THREAD

**Issue by iisa** [internetarchive/iaux#318]
Problem:
When main menu closes and secondary menu is open, secondary menu does not close. See gif
![main-menu-close-2nd](https://user-images.githubusercontent.com/7840857/66338449-fe254e00-e8f5-11e9-8cbc-d51de1cdb3dc.gif)

Acceptance:
Secondary menu rolls up and closes when main menu is closed

**Comment by d80ep08th** [comment]
hey
is this issue still not closed?
I can help

**Comment by shaneriley** [comment]
Looks like this has been fixed.
