### ISSUE TITLE
Menu: Close menu if open when user clicks or taps away

### ISSUE THREAD

**Issue by iisa** [internetarchive/iaux#329]
In the new mobile nav component, when a click or tap event happens outside of the mobile nav while a menu is open, all menus should close.

**Comment by iamshreyash** [comment]
I am new to opensource. Which files should I refer to if I want to resolve this issue.

**Comment by maze-runnar** [comment]
@iisa can you please help me with files for the issue?

**Comment by CapriciousRebel** [comment]
Hello, I would like to work on this issue, can someone please guide me?

**Comment by shaneriley** [comment]
This is already fixed in #394
