### ISSUE TITLE
Login page: email and password fields have different appearances

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#34]
**Is your feature request related to a problem? Please describe.**
The email and password fields are of different widths and padding as the two have different styles applied to them.
![Screen Shot 2019-03-25 at 10 17 08 PM](https://user-images.githubusercontent.com/30471843/54938119-c6ebe280-4f4b-11e9-8cc8-8745d9494d56.png)

Style applied to password field
![Screen Shot 2019-03-25 at 10 25 47 PM](https://user-images.githubusercontent.com/30471843/54938725-f94a0f80-4f4c-11e9-93b0-65b1a20d7757.png)

**Describe the solution you'd like**
Both fields should share similar styles.

**Comment by MonilBhavsar** [comment]
Also the login container needs to be framed inside a proper container which results in the better UI.

**Current login page:-**

<img width="1040" alt="Screenshot 2019-03-26 at 7 13 28 PM" src="https://user-images.githubusercontent.com/32012005/55001900-9b283580-4ffb-11e9-8bb3-847a27eb64b6.png">

**Expected Login Page:**

<img width="1040" alt="Screenshot 2019-03-26 at 7 13 10 PM" src="https://user-images.githubusercontent.com/32012005/55001954-b72bd700-4ffb-11e9-8a06-de85c0820eb7.png">

**I would like to work and resolve this issue.**

**Comment by pezvi** [comment]
Thanks for raising this issue. It's currently being addressed internally, so I'll go ahead and close this issue here.
