### ISSUE TITLE
Semantics: Remove instances of <br>

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#35]
**Is your feature request related to a problem? Please describe.**
In many places on the website, especially for label and input fields (Signup page, Login page) `<br>` tags are used to keep items on separate lines which go against good practice.

**Describe the solution you'd like**
The  `<br>`s can be removed and items kept on different lines by changing `display: inline-block` to `display: block`.

**Comment by iisa** [comment]
Thanks for pointing this out, @koderjoker!  We are in current development of a better layout of the login and signup pages as I type.

This is a primary principle we should all follow moving forward.
