### ISSUE TITLE
Move all components from ia-components/sandbox => ia-components/components

### ISSUE THREAD

**Issue by iisa** [internetarchive/iaux#360]
**Task Details**
Currently, we have 2 directories that contain UI components inside of `ia-components` directory: `live` and `sandbox`.

We no longer need the differentiation between the two as all components in sandbox are now live and being used either in archive.org or dweb project.

live vs sandbox was an experiment on staging components into master while they are not fully fleshed out, at this point we see that it is no longer working for us. 

**Task**:
- Move all components from ia-components/sandbox => ia-components/components 
- remove `live` directory
- `components` should be the only directory that houses UI components

**Verification**

- RUN storybook in ia-components and make sure all stories run.
- there is no more `live` directory
- there is only `components` directory

**Comment by mitra42** [comment]
Whats the ETA on this iisa - would like to do a PR with all my stuff to merge so that happens before the refactor ?

**Comment by iisa** [comment]
@mitra42 no hard time frame, just starting to create tickets around repo clean up. we will definitely get your fixes in before this task gets in.

**Comment by mitra42** [comment]
Great - is making ia-components its own repo a separate task for later (I.e. pulling it out of the lerna mess)

**Comment by RisingGeek** [comment]
Is anybody doing this task? If not, @iisa Could you please assign the task to me?

**Comment by crew-guy** [comment]
Hi ! Is this issue resolved ? I would really like to work on it .... 😄

**Comment by iisa** [comment]
hi, thanks so much for being able to lend a hand. this issue was just resolved.
