### ISSUE TITLE
Bottom to top button

### ISSUE THREAD

**Issue by aashimgarg** [internetarchive/iaux#372]
There is no bottom to top button in the main page of this website . This feature will be helpful for the user to get to the top of the page easily .

**Comment by aashimgarg** [comment]
@rchrd2

**Comment by kartik918** [comment]
You should rename the issue to "Implement scroll-to-top button" or something to better describe the idea.

**Comment by KaranKS** [comment]
@kartik918 can you assign this to me ?

**Comment by kartik918** [comment]
If you want to get involved, you can start from the goals list in projects section.

**Comment by KaranKS** [comment]
> There is no bottom to top button in the main page of this website . This feature will be helpful for the user to get to the top of the page easily .

What do you mean by "main page"?

**Comment by SunnySaheb** [comment]
is it already finished, i want to work on this. can anyone kindly tell

**Comment by harshit0603** [comment]
how to find html file of this site

**Comment by AkshadK7** [comment]
Hey, is this Feature Request issue already Resolved ? @aashimgarg
