### ISSUE TITLE
Making Login-Signup Page UI better 

### ISSUE THREAD

**Issue by MonilBhavsar** [internetarchive/iaux#40]
**Description**
> What problem are we solving? What does the experience look like today? What are the symptoms? Please describe the component/story/add on related to the issue.

The login page and signup page has some design an UI flaws, they can be solved if the input elements are made of equal width and fitted inside the container(As in expectation image)

**Evidence / Screenshot (if possible)**

<img width="1040" alt="Screenshot 2019-03-26 at 7 13 28 PM" src="https://user-images.githubusercontent.com/32012005/55063306-b8addb80-509d-11e9-99e4-4693541cec4f.png">

**Expectation**
> What should by happening? What will it look like / how will it behave?
<img width="1040" alt="Screenshot 2019-03-26 at 7 13 10 PM" src="https://user-images.githubusercontent.com/32012005/55063318-be0b2600-509d-11e9-9479-db31824d8554.png">

**Comment by sagban** [comment]
Hello @MonilBhavsar 
I would like to fix this issue.
Please, assign this to me.

**Comment by mekarpeles** [comment]
No design flaws were actually mentioned in the description no evidence was provided the proposal is an improvement.

The first step of iaux should be migrating our components from the archive.org website (as is) into a standalone component within the iaux repo.

Design proposals should be clearly labeled as such and presented for discussion.

Closing until these requirements are met
