### ISSUE TITLE
build Donation banners component 

### ISSUE THREAD

**Issue by maze-runnar** [internetarchive/iaux#406]
**Task Details**

build a donation banner component .
**Verification**
I want to work on this.

**Stakeholders**

> @shaneriley @jbuckner @iisa please help me in this

**Comment by sarthak-m-das** [comment]
Can I work on this

**Comment by sarthak-m-das** [comment]
I would like to work on this.

**Comment by bharathbiju** [comment]
@maze-runnar could you give a basic layout for the donation banner , i would like to work on it
