### ISSUE TITLE
Error when demoing scrubber-bar with storybook

### ISSUE THREAD

**Issue by Swapnil-2001** [internetarchive/iaux#529]
**Description**

> What problem are we solving? What does the experience look like today? What are the symptoms? How can one reproduce the problem?

Running `yarn storybook` inside _**packages/scrubber-bar**_ throws up an error.

**Evidence / Screenshot (if possible)**

> Include evidence of the problem or provide a screenshot.

![Storybook - Google Chrome 17-03-2021 20_24_06](https://user-images.githubusercontent.com/53232360/111488938-b6982800-875f-11eb-8126-7e1fd15febb8.png)

**Context**

> What operating system? What browser type and version?

Windows 10, Google Chrome Version 89.0.4389.82

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

This is likely due to a faulty import.

**Stakeholders**

> @-tag any stakeholders of this bug

**Comment by jbuckner** [comment]
Replacing this with https://github.com/internetarchive/iaux/issues/573
