### ISSUE TITLE
Error when running 'yarn storybook' from expandable-search-bar

### ISSUE THREAD

**Issue by Swapnil-2001** [internetarchive/iaux#534]
**Description**

Running `yarn storybook` from **packages/expandable-search-bar** throws up errors.

> What problem are we solving? What does the experience look like today? What are the symptoms? How can one reproduce the problem?

**Evidence / Screenshot (if possible)**

![Hyper 18-03-2021 23_43_56](https://user-images.githubusercontent.com/53232360/111681425-35b55b00-8849-11eb-8c37-56a2a64de058.png)

> Include evidence of the problem or provide a screenshot.

**Expectation**

> What should be happening? What will it look like / how will it behave when fixed?

**Context**

> What operating system? What browser type and version?

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Stakeholders**

> @-tag any stakeholders of this bug

**Comment by jbuckner** [comment]
Replacing this with https://github.com/internetarchive/iaux/issues/574
