### ISSUE TITLE
Obsolete information in README.md

### ISSUE THREAD

**Issue by crew-guy** [internetarchive/iaux#536]
**Description**

> What problem are we solving? What does the experience look like today? What are the symptoms? How can one reproduce the problem?

The README.md has details about only 4 packages instead of  **all** the packages. 

**Evidence / Screenshot (if possible)**

> Include evidence of the problem or provide a screenshot.

![Screenshot from 2021-03-19 07-26-24](https://user-images.githubusercontent.com/69717009/111720860-bfcee500-8884-11eb-8bce-3e3a4ab45bff.png)

**Expectation**

> What should be happening? What will it look like / how will it behave when fixed?

Just add some documentation for all the mentioned packages so that it is easier for newcomers to onboard the project and familiarize with the coddebase easily 

**Context**

> What operating system? What browser type and version?

1. OS : Ubuntu 20.0.4, 
2. Browser : Google Chrome
3. Browser version : 88.0.4324.150

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

Complete the loopholes in the documentation.

**Stakeholders**

> @-tag any stakeholders of this bug

**Comment by crew-guy** [comment]
May I please work on this issue ?

**Comment by crew-guy** [comment]
I will be shortly adding a PR to close this

**Comment by Priyaraj17** [comment]
Is this issue open? May I work on this?

**Comment by crew-guy** [comment]
I am working on this. Just need an approval to make my PR
