### ISSUE TITLE
Remove storybook from scrubber-bar package

### ISSUE THREAD

**Issue by jbuckner** [internetarchive/iaux#573]
**Task Details**

> We don't use storybook for demoing `scrubber-bar` so remove it as a dependency

**Verification**

> Storybook, its scripts, and dependencies are removed from package.json and instructions removed from the readme

**Stakeholders**

> @jbuckner

Replaces https://github.com/internetarchive/iaux/issues/529

**Comment by soham4abc** [comment]
I can do this If possible pls assign

**Comment by jbuckner** [comment]
It's yours!
