### ISSUE TITLE
Remove storybook from expandable-search-bar package

### ISSUE THREAD

**Issue by jbuckner** [internetarchive/iaux#574]
**Task Details**

> We don't use storybook for demoing `expandable-search-bar` so remove it as a dependency

**Verification**

> Storybook, its scripts, and dependencies are removed from package.json and instructions removed from the readme

**Stakeholders**

> @jbuckner

Replaces https://github.com/internetarchive/iaux/issues/534

**Comment by soham4abc** [comment]
I can work in this issue
