### ISSUE TITLE
Missing Petabox logo

### ISSUE THREAD

**Issue by ananay** [internetarchive/iaux#75]
**Description**
There is no image for Petabox on [https://archive.org/projects/](https://archive.org/projects/)
The image URL currently renders a 404.

**Evidence / Screenshot (if possible)**
![image](https://user-images.githubusercontent.com/5569219/55798273-68fae700-5a83-11e9-8f50-a85e019722af.png)

**Expectation**
Create a logo for Petabox or add an image of Petabox itself:
![image](https://user-images.githubusercontent.com/5569219/55798319-80d26b00-5a83-11e9-977c-f9a035adbc1d.png)

**Comment by ananay** [comment]
I've also created a logo for Petabox just in case it is needed. Comments and suggestions are welcome!

![Petabox Logo](https://user-images.githubusercontent.com/5569219/55799600-9b5a1380-5a86-11e9-80ff-bd062c68abb4.png)

**Comment by ananay** [comment]
I've created a logo for Petabox incase one is required. Comments and suggestions are welcome!

![Petabox Logo](https://user-images.githubusercontent.com/5569219/55799763-0277c800-5a87-11e9-807b-f035cca596c0.png)


@bfalling @iisa

**Comment by pezvi** [comment]
Thank you for raising this issue (and for pinging us again when you didn't hear back).

There's definitely supposed to be a petabox image in that spot, which appears to have gone missing earlier this year. I've opened an issue on our internal system to address this bug.

Although we have an image to use for petabox, I also wanted to mention I appreciated you proposing a logo in case we needed one. Thanks!

**Comment by mekarpeles** [comment]
Also, a great way to see what that image *was* is using the Wayback Machine!!

http://web.archive.org/web/20160306232531/http://archive.org/projects/

There it is!

![image](https://user-images.githubusercontent.com/978325/56331689-3cf5fa80-6142-11e9-95c8-02327f5ffe49.png)
