### ISSUE TITLE
  Upgrade to Storybook 5

### ISSUE THREAD

**Issue by shreyansh23** [internetarchive/iaux#80]
Is your feature request related to a problem? Please describe.

Upgrade to Storybook 5

Currently, Storybook 4 is being used. Storybook 5 has been out and is the biggest release from @storybooks

Storybook 5 offers a lot of new and useful features. For more information read the official blog post https://medium.com/storybookjs/storybook-5-0-db1d0f9c83b8

Stakeholders
@iisa @bfalling

**Comment by iisa** [comment]
closing. we have a new plan to move to Storybook 5.
